### ISSUE TITLE
data source OpenECry still alive?

### ISSUE THREAD

**Issue by leo90skk** [leo90skk/qdms#22]
The project QDMSServer holds a datasource for OpenECry.

The [documentation site](http://pro.openecry.com/api/api/index.html) and the main domain openecry.com is down.

Should we remove the data source? or did they changed just the name and we can use annother API URL?

**Comment by qusma** [comment]
Looks like they were acquired by Gain Capital. Can't find details on the API on their site though. I say remove it.
