### ISSUE TITLE
Add support for HistoricalDataSource EODData (http://eoddata.com)

### ISSUE THREAD

**Issue by underwater** [leo90skk/qdms#29]
I have worked with http://eoddata.com/ which is a low cost site for end of day (and historical prices), and could perhaps try to implement IHistoricalDataSource for this data provider?

**Comment by leo90skk** [comment]
Please create a pull request with the new historical data source from your fork...

**Comment by underwater** [comment]
​Thanks for the reminder, I will do so​

**Comment by leo90skk** [comment]
@underwater Is there a test account which we can use for testing purpose?

See https://ci.appveyor.com/project/leo90skk/qdms/build/0.9.2.110-master

**Comment by underwater** [comment]
Hi there, apologize for late response, regrettably, there is no longer a
test account, as they have raised their prices, and I had no more use for
it.

**Comment by leo90skk** [comment]
Sad top hear that. OK, then I will change the source that the DataSource is not added as default and disable the unit test. Maybe some other user will need it...

**Comment by leo90skk** [comment]
I committed the push request with the EOD data source. It is added optionally and will be loaded if someone adds the login credentials to the app.config.

Unit test is disabled but could be started manually. I didn't tested it.
