### ISSUE TITLE
Unit Tests causing error "Exception encountered unloading AppDomain"

### ISSUE THREAD

**Issue by leo90skk** [leo90skk/qdms#57]
Some Unit Tests are causing the error `Exception encountered unloading AppDomain` after passing with OK.

As I read in https://github.com/nunit/nunit/issues/329, this might be caused by the unit test itself.

I disabled all theese unit tests. All are using the NetMQ library - so probably the bug comes from there...

### In class `HistoricalDataServerTest`
*- Complete class -*
- [ ] HistoricalDataRequestsAreForwardedToTheBroker
- [ ] StartServerStartsTheServer
- [ ] StopServerStopsTheServer
- [ ] DataPushRequestIsForwardedToLocalStorage
- [ ] AcceptAvailableDataRequestsAreForwardedToTheHistoricalDataBroker
- [ ] SendsErrorMessageWhenExceptionIsRaisedByBrokerOnHistoricalDataRequest

### In class `RealTimeDataServerTest`
*- Complete class -*
- [ ] ServerCorrectlyForwardsRealTimeDataRequestsToBroker
- [ ] ServerCorrectlyForwardsCancellationRequestsToBroker
- [ ] ServerReturnsErrorToClientIfNoInstrumentIdIsSet
- [ ] ServerReturnsErrorToClientIfNoInstrumentDatasourceIsSet
- [ ] ServerForwardsErrorToClientIfExceptionIsThrownInRequestRealTimeData
- [ ] ServerCorrectlyForwardsRealTimeData
- [ ] StartServerStartsTheServer
- [ ] StopServerStopsTheServer

### In class `InstrumentsServerTest`
*- all Unit Tests -*
- [ ] SearchesForInstrumentsWithTheCorrectParameters
- [ ] RequestForAllInstrumentsIsForwardedCorrectly
- [ ] ExpressionSearchIsTransmittedCorrectly

**Comment by leo90skk** [comment]
Would be nice if someone can help here since I have not so much experience in NetMQ...

**Comment by qusma** [comment]
This seems to be it: https://github.com/zeromq/netmq/issues/516

But looking at the tests we definitely dispose the pollers in the TearDown...though not the sockets, it seems. Perhaps that's the issue. If that doesn't solve it, we could just throw in NetMQConfig.Cleanup(); and be done with it. Does seem a bit hacky though.

Is there a way to get this AppDomain error locally? When I run the tests I don't see it.

**Comment by leo90skk** [comment]
@qusma You have to download the nunit3-console. Than you can build the test project and just run it in the same way as it is done in appveyor. You will get the error in the console.

**Comment by qusma** [comment]
OK, I tried fiddling around a bit with the disposal methods, but I couldn't get it to work. NetMQConfig.Cleanup() works.

**Comment by leo90skk** [comment]
Fixed with #58
